name: flutter_query
description: Widgets that help state management of asynchronous operations such as sending HTTP requests, getting the response, and caching the result.
version: 0.3.7
repository: https://github.com/jezsung/query/tree/main/packages/flutter_query

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.10.0
  clock: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  meta: ^1.9.1
  provider: ^6.0.5
  query_core: #^0.2.1 ## we need to update the core package here.
    path: ../query_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.26.3
