name: flutter_query
description: Widgets that help state management of asynchronous operations such as sending HTTP requests, getting the response, and caching the result.
version: 0.3.7
repository: https://github.com/jezsung/query/tree/main/packages/flutter_query

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  async: ^2.10.0
  clock: ^1.1.2
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  meta: ^1.16.0

dev_dependencies:
  fake_async: ^1.3.3
  flutter_hooks_test: ^2.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  test: ^1.25.15

import_sorter:
  emojis: false
  comments: false
