name: CI

on:
  pull_request:
    paths:
      - 'packages/flutter_query/**'
      - '!packages/flutter_query/example/**'
      - '!**/*.md'
      - '!**/LICENSE'
  push:
    paths:
      - 'packages/flutter_query/**'
      - '!packages/flutter_query/example/**'
      - '!**/*.md'
      - '!**/LICENSE'
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/flutter_query

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        channel:
          - stable
        flutter-version:
          - 3.32.0
          - 3.35.0
          - 3.38.0
      fail-fast: false
    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - run: flutter pub get

      - run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - run: flutter pub run import_sorter:main --exit-if-changed

      - run: dart format --output none --set-exit-if-changed .

      - run: flutter test --coverage

      - name: Upload coverage to Codecov
        if: matrix.flutter-version == '3.38.0'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de #v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: packages/flutter_query/coverage/lcov.info
          flags: flutter_query
          fail_ci_if_error: false
