name: Documentation CI/CD

on:
  pull_request:
    paths:
      - 'docs/**'
      - '!docs/README.md'
  push:
    paths:
      - 'docs/**'
      - '!docs/README.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: docs

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: docs/package.json
          cache: true
          cache-dependency-path: docs/pnpm-lock.yaml

      - uses: actions/setup-node@v6
        with:
          node-version-file: docs/package.json
          cache: 'pnpm'
          cache-dependency-path: docs/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - name: Check types, formatting, linting, and build
        run: |
          pnpm dlx concurrently --names "typecheck,format,lint,build" \
            "pnpm run typecheck" \
            "pnpm run format:check" \
            "pnpm run lint:check" \
            "pnpm run build"

      - if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/out
          retention-days: 1

  build:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: docs-build
          path: docs/out

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/out

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
