name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '!.prettierignore'
      - '!.prettierrc.js'
      - '!eslint.config.mjs'
      - 'docs/**'
      - '!docs/README.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: docs/package.json
          cache: true
          cache-dependency-path: docs/pnpm-lock.yaml

      - uses: actions/setup-node@v6
        with:
          node-version-file: docs/package.json
          cache: 'pnpm'
          cache-dependency-path: docs/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: docs

      - run: pnpm build
        working-directory: docs

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/out

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
